export { default as FirstBanner } from './FirstBanner'
export { default as Metrics } from './Metrics'
export { default as ThirdBanner } from './Thirdbanner'
export { default as Partnership } from './Partnership'
export { default as SecondBanner } from './SecondBanner'
export { default as CommercesSlider } from './CommercesSlider'
