export const homeId = 'cG9zdDozNw=='
export const aboutId = 'cG9zdDo3Nw=='
export const forYouId = 'cG9zdDoyMTY='
export const forBusinessId = 'cG9zdDoyMjA='
export const proId = 'cG9zdDoyOTE='
export const blogId = 'cG9zdDozMzk='
